POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Masxterias blog",
    "author": "Maximiliano Morales",
    "url": "https://maximilianomorales.com",
    "likes": 0
}
